theme: jekyll-theme-minimal
title: The Dojo4 Playbook
description: This is how we do it yall. Mostly Beta but some Alpha - aka a WIP...
license: This material is licensed under Creative Commons Attribution 4.0 International (CC BY 4.0) allowing reusers to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator. The license allows for commercial use.
